### ISSUE TITLE
Create an Interactive Readme.md

### ISSUE THREAD

**Issue by stephin007** [stephin007/currencyconvertor#7]
Whoever is reading this, this project has a by default Readme.md which needs to replaced by an interactive one.

**For more details contact me!**

**Comment by Goodiec** [comment]
I would like to contribute to this

**Comment by LuizHAP** [comment]
I have some projects that look like an interesting layout, do you have any that you like?

**Comment by stephin007** [comment]
hey @Goodiec 
Yes,Please do!

**Comment by stephin007** [comment]
hey @LuizHAP cwn you send me the layout?
Would like to see that

**Comment by LuizHAP** [comment]
@stephin007 https://github.com/LuizHAP/proffy/blob/master/README.md

**Comment by stephin007** [comment]
Yes @LuizHAP this template is great, please go ahead with this

**Comment by LuizHAP** [comment]
@stephin007 please dont forget to change the topic (https://hacktoberfest.digitalocean.com/hacktoberfest-update)

**Comment by stephin007** [comment]
Done @LuizHAP

**Comment by LuizHAP** [comment]
Finished @stephin007, i only need to change the picture after this

**Comment by stephin007** [comment]
Okay, @LuizHAP i am merging the rest of the content, please raise another PR for that
