### ISSUE TITLE
Add a full form/flags for the currencies

### ISSUE THREAD

**Issue by stephin007** [stephin007/currencyconvertor#8]
When clicked on the drop-down to select currencies, it only shows abbreviations for the currency.
It should rather show the flag of the country or name of the country.

**Comment by jigs1212** [comment]
@stephin007 I would like to contribute on this.

**Comment by stephin007** [comment]
hey @jigs1212 Yes , please do.
Please let me know if you get stuck at some point.

All you have to do is to
1. cd into the project folder.
2. npm install.
3. npm start.

**Comment by jigs1212** [comment]
Hey @stephin007 ,  I was able to setup and run the program thanks.

How do you plan to add the country name? 

1.Using other api which may provide both name and currency symbols etc.
2. Or to have a local list which contains the name of the country and the currency code?

**Comment by stephin007** [comment]
Hey, @jigs1212 its great to hear from the community.

Having the country names and Abbreviations locally would be the best in our scenario and also can we use another api for getting only the symbols for our locally stored country names. 

Will  it slow down our app by doing this? Or do you have any other idea

**Comment by stephin007** [comment]
hey @jigs1212 any progress? anywhere i can help you!

**Comment by jigs1212** [comment]
Hey @stephin007 

Currently I think We can use a secondary api, with the existing one.
`https://restcountries.eu/rest/v2/all` 
and map them together.

**Comment by stephin007** [comment]
Awesome @jigs1212  That would be Great, but please do note one thing that, the exhnge rates api is returning only 33 countries, so make sure when you use the new api you get that same number of countries, otherwise you will/might face errors

**Comment by jigs1212** [comment]
> Awesome @jigs1212 That would be Great, but please do note one thing that, the exhnge rates api is returning only 33 countries, so make sure when you use the new api you get that same number of countries, otherwise you will/might face errors

@stephin007 are we sure that the exchange rates api will return only 33 countries.

Currently what i have planned is.
1. Hit both the apis.
2. on the basis of exchange rate apis, modify the object by mapping the response from the secondary api. ( which will only have the data related to exchange rate apis and no other data )
3. And then use the same.

`Will update the modified object here`

**Comment by stephin007** [comment]
Yes @jigs1212 , i remember the api data, it gave only 33countries, i dont remember clearly.

But please move forward with the plan! 🔥

**Comment by jigs1212** [comment]
@stephin007 
I went through the logic and face some difficulties in implementing.

Earlier there were 33 countries in the original API.
And when I implemented the secondary API, there are 101 countries.
This is caused due to, some countries use the same currency as the one in the original API.

**Comment by stephin007** [comment]
> @stephin007
> I went through the logic and face some difficulties in implementing.
> 
> Earlier there were 33 countries in the original API.
> And when I implemented the secondary API, there are 101 countries.
> This is caused due to, some countries use the same currency as the one in the original API.

Oh alright! @jigs1212 you can  take your time to resolve the issue. if any doubts you can ask!

**Comment by stephin007** [comment]
@jigs1212 I just saw your PR.....Did you resolve the issue? or are you gonna continue?

**Comment by jigs1212** [comment]
@stephin007 there is no issue as such but we have more countries now which use repetitive currencies.

**Comment by stephin007** [comment]
Thats not a issue @jigs1212
